### ISSUE TITLE
Dynambo DB required?

### ISSUE THREAD

**Issue by basant-gurung** [robertlabrie/logstash-input-rds#3]
Hi Robert,

Do we need a dynamo db beforehand? if yes, where should we keep the Dynamo db credentials so that this plugin picks it to create its table?

**Comment by robertlabrie** [comment]
Hi @basant-gurung 

It will create the table automatically if it doesn't already exist: https://github.com/robertlabrie/logstash-input-multirds/blob/master/lib/logstash/inputs/multirds.rb#L31

As for the credentials, I used an IAM policy on the instance that had permissions to manage dynamo if that's not an option for you I expect it would go in `/home/logstash/.aws/credentials` the plugin just uses the AWS Ruby SDK so wherever they say to put the creds is where to put them
